# Generated by Django 5.0.6 on 2024-07-08 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0002_data_sorted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='data_sorted',
        ),
        migrations.DeleteModel(
            name='uploaded_data_truncated_og',
        ),
    ]
