# Generated by Django 5.0.6 on 2024-07-03 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0010_alter_originaldata_course_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OriginalData',
            new_name='uploaded_data',
        ),
        migrations.DeleteModel(
            name='ExcelData',
        ),
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
