# Generated by Django 5.0.6 on 2024-07-03 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fileupload', '0011_rename_originaldata_uploaded_data_delete_exceldata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploaded_data',
            name='backlog_attempt_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='uploaded_data',
            name='batch_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploaded_data',
            name='class_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploaded_data',
            name='credit_point_earned',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='uploaded_data',
            name='credit_point_offered',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='uploaded_data',
            name='exam_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uploaded_data',
            name='exam_type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uploaded_data',
            name='is_backlog',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='uploaded_data',
            name='is_pass',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='uploaded_data',
            name='max_marks',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='uploaded_data',
            name='obt_grade',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='uploaded_data',
            name='obt_marks',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='uploaded_data',
            name='reg_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uploaded_data',
            name='report_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploaded_data',
            name='roll_no',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uploaded_data',
            name='rv_marks',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='uploaded_data',
            name='rv_updated',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='uploaded_data',
            name='semester',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='uploaded_data',
            name='student_batch_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploaded_data',
            name='student_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploaded_data',
            name='subject_code',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='uploaded_data',
            name='subject_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='uploaded_data',
            name='subject_type',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
